"""Answer generation.

If OPENAI_API_KEY is set, answers are generated by any OpenAI-compatible chat API
(set OPENAI_BASE_URL to point at another provider). Without a key the app still
works: it streams back the best-matching passages, so you can try retrieval and
the streaming UI with zero setup.
"""
from __future__ import annotations

import json
import os
from collections.abc import AsyncIterator

import httpx

from retriever import Chunk

SYSTEM_PROMPT = (
    "You answer questions using only the numbered context passages provided. "
    "Cite passages inline like [1] or [2]. If the context does not contain the answer, "
    "say you don't know. Keep answers short."
)


def build_messages(question: str, hits: list[Chunk]) -> list[dict]:
    context = "\n\n".join(f"[{i + 1}] ({c.source} / {c.heading})\n{c.text}" for i, c in enumerate(hits))
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"},
    ]


async def stream_answer(question: str, hits: list[Chunk]) -> AsyncIterator[str]:
    if not hits:
        yield "I couldn't find anything about that in the documents."
        return

    key = os.getenv("OPENAI_API_KEY")
    if not key:
        # Offline mode: stream the top passage word by word so the UI behaves the same.
        yield "(offline mode, no LLM key set) Most relevant passage [1]:\n\n"
        for word in hits[0].text.split(" "):
            yield word + " "
        return

    base = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.getenv("LLM_MODEL", "gpt-4o-mini")
    payload = {"model": model, "stream": True, "messages": build_messages(question, hits)}
    async with httpx.AsyncClient(timeout=60) as client:
        async with client.stream(
            "POST", f"{base}/chat/completions", json=payload,
            headers={"Authorization": f"Bearer {key}"},
        ) as resp:
            resp.raise_for_status()
            async for line in resp.aiter_lines():
                if not line.startswith("data: ") or line.endswith("[DONE]"):
                    continue
                delta = json.loads(line[6:])["choices"][0]["delta"].get("content")
                if delta:
                    yield delta
